package com.gwac.model;
// Generated 2015-10-2 9:40:37 by Hibernate Tools 3.6.0

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * DataProcessMachine generated by hbm2java
 */
@Entity
@Table(name = "camera", schema = "public"
)
public class Camera implements java.io.Serializable {
  private int cameraId;
  private String name;
  private Integer mountId;
  private Integer curProcessNumber;
  private Date monitorImageTime;
  private Date lastActiveTime;
  private Integer curSkyId;
  private Integer firstRecordNumber;
  private Integer status;
  private String comment;
  private String cameraType;
  
  private Integer coverStatus;
  private Integer focus;
  private Float coolget;
  private String filter;
  private Integer errcode;
  private String imgType;
  private String objName;
  private Integer frmNo;
  private String fileName;
  
  private Integer linked;
  private Integer coverLinked;
  private Date cameraUtc;
  private Date cameraCoverUtc;
  private Integer cameraCoverErrcode;
  
  private String gid;
  private String uid;
  private String cid;

  public Camera() {
  }

  public Camera(int cameraId) {
    this.cameraId = cameraId;
  }

  @Id
  @GenericGenerator(name = "generator", strategy = "seqhilo", parameters = {
    @Parameter(name = "max_lo", value = "49"),
    @Parameter(name = "sequence", value = "camera_id_seq")})
  @GeneratedValue(generator = "generator")
  @Column(name = "camera_id", unique = true, nullable = false)
  public int getCameraId() {
    return this.cameraId;
  }

  public void setCameraId(int cameraId) {
    this.cameraId = cameraId;
  }

  @Column(name = "name")
  public String getName() {
    return this.name;
  }

  public void setName(String name) {
    this.name = name;
  }

  @Column(name = "cur_process_number")
  public Integer getCurProcessNumber() {
    return this.curProcessNumber;
  }

  public void setCurProcessNumber(Integer curProcessNumber) {
    this.curProcessNumber = curProcessNumber;
  }

  @Temporal(TemporalType.TIMESTAMP)
  @Column(name = "monitor_image_time", length = 29)
  public Date getMonitorImageTime() {
    return this.monitorImageTime;
  }

  public void setMonitorImageTime(Date monitorImageTime) {
    this.monitorImageTime = monitorImageTime;
  }

//  @Temporal(TemporalType.TIMESTAMP)
  @Column(name = "last_active_time", length = 29)
  public Date getLastActiveTime() {
    return this.lastActiveTime;
  }

  public void setLastActiveTime(Date lastActiveTime) {
    this.lastActiveTime = lastActiveTime;
  }

  @Column(name = "first_record_number")
  public Integer getFirstRecordNumber() {
    return this.firstRecordNumber;
  }

  public void setFirstRecordNumber(Integer firstRecordNumber) {
    this.firstRecordNumber = firstRecordNumber;
  }

  /**
   * @return the mountId
   */
  @Column(name = "mount_id")
  public Integer getMountId() {
    return mountId;
  }

  /**
   * @param mountId the mountId to set
   */
  public void setMountId(Integer mountId) {
    this.mountId = mountId;
  }

  /**
   * @return the status
   */
  @Column(name = "status")
  public Integer getStatus() {
    return status;
  }

  /**
   * @param status the status to set
   */
  public void setStatus(Integer status) {
    this.status = status;
  }

  /**
   * @return the comment
   */
  @Column(name = "comment")
  public String getComment() {
    return comment;
  }

  /**
   * @param comment the comment to set
   */
  public void setComment(String comment) {
    this.comment = comment;
  }

  /**
   * @return the cameraType
   */
  @Column(name = "camera_type")
  public String getCameraType() {
    return cameraType;
  }

  /**
   * @param cameraType the cameraType to set
   */
  public void setCameraType(String cameraType) {
    this.cameraType = cameraType;
  }

  @Column(name = "cur_sky_id")
  public Integer getCurSkyId() {
    return curSkyId;
  }

  public void setCurSkyId(Integer curSkyId) {
    this.curSkyId = curSkyId;
  }

  @Column(name = "focus")
  public Integer getFocus() {
    return focus;
  }

  public void setFocus(Integer focus) {
    this.focus = focus;
  }

  @Column(name = "coolget")
  public Float getCoolget() {
    return coolget;
  }

  public void setCoolget(Float coolget) {
    this.coolget = coolget;
  }

  @Column(name = "filter")
  public String getFilter() {
    return filter;
  }

  public void setFilter(String filter) {
    this.filter = filter;
  }

  @Column(name = "img_type")
  public String getImgType() {
    return imgType;
  }

  public void setImgType(String imgType) {
    this.imgType = imgType;
  }

  @Column(name = "obj_name")
  public String getObjName() {
    return objName;
  }

  public void setObjName(String objName) {
    this.objName = objName;
  }

  @Column(name = "frm_no")
  public Integer getFrmNo() {
    return frmNo;
  }

  public void setFrmNo(Integer frmNo) {
    this.frmNo = frmNo;
  }

  @Column(name = "file_name")
  public String getFileName() {
    return fileName;
  }

  public void setFileName(String fileName) {
    this.fileName = fileName;
  }

  /**
   * @return the coverStatus
   */
  @Column(name = "cover_status")
  public Integer getCoverStatus() {
    return coverStatus;
  }

  /**
   * @param coverStatus the coverStatus to set
   */
  public void setCoverStatus(Integer coverStatus) {
    this.coverStatus = coverStatus;
  }

  /**
   * @return the errcode
   */
  @Column(name = "errcode")
  public Integer getErrcode() {
    return errcode;
  }

  /**
   * @param errcode the errcode to set
   */
  public void setErrcode(Integer errcode) {
    this.errcode = errcode;
  }

  /**
   * @return the linked
   */
  @Column(name = "linked")
  public Integer getLinked() {
    return linked;
  }

  /**
   * @param linked the linked to set
   */
  public void setLinked(Integer linked) {
    this.linked = linked;
  }

  /**
   * @return the coverLinked
   */
  @Column(name = "cover_linked")
  public Integer getCoverLinked() {
    return coverLinked;
  }

  /**
   * @param coverLinked the coverLinked to set
   */
  public void setCoverLinked(Integer coverLinked) {
    this.coverLinked = coverLinked;
  }

  /**
   * @return the cameraUtc
   */
  @Column(name = "camera_utc")
  public Date getCameraUtc() {
    return cameraUtc;
  }

  /**
   * @param cameraUtc the cameraUtc to set
   */
  public void setCameraUtc(Date cameraUtc) {
    this.cameraUtc = cameraUtc;
  }

  /**
   * @return the cameraCoverUtc
   */
  @Column(name = "camera_cover_utc")
  public Date getCameraCoverUtc() {
    return cameraCoverUtc;
  }

  /**
   * @param cameraCoverUtc the cameraCoverUtc to set
   */
  public void setCameraCoverUtc(Date cameraCoverUtc) {
    this.cameraCoverUtc = cameraCoverUtc;
  }

  /**
   * @return the cameraCoverErrcode
   */
  @Column(name = "camera_cover_errcode")
  public Integer getCameraCoverErrcode() {
    return cameraCoverErrcode;
  }

  /**
   * @param cameraCoverErrcode the cameraCoverErrcode to set
   */
  public void setCameraCoverErrcode(Integer cameraCoverErrcode) {
    this.cameraCoverErrcode = cameraCoverErrcode;
  }


  /**
   * @return the gid
   */
  @Column(name = "gid")
  public String getGid() {
    return gid;
  }

  /**
   * @param gid the gid to set
   */
  public void setGid(String gid) {
    this.gid = gid;
  }

  /**
   * @return the uid
   */
  @Column(name = "uid")
  public String getUid() {
    return uid;
  }

  /**
   * @param uid the uid to set
   */
  public void setUid(String uid) {
    this.uid = uid;
  }

  /**
   * @return the cid
   */
  @Column(name = "cid")
  public String getCid() {
    return cid;
  }

  /**
   * @param cid the cid to set
   */
  public void setCid(String cid) {
    this.cid = cid;
  }

}
