package com.gwac.model;
// Generated 2016-12-4 18:51:52 by Hibernate Tools 3.6.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * MoveObjectRecord generated by hbm2java
 */
@Entity
@Table(name = "move_object_record", schema = "public"
)
public class MoveObjectRecord implements java.io.Serializable {

  private long oorId;
  private Long ffId;
  private Integer objDayNum;
  private Integer recFileNum;
  private Long movId;

  public MoveObjectRecord() {
  }

  public MoveObjectRecord(long oorId) {
    this.oorId = oorId;
  }

  @Id
  @Column(name = "oor_id", unique = true, nullable = false)
  public long getOorId() {
    return this.oorId;
  }

  public void setOorId(long oorId) {
    this.oorId = oorId;
  }

  @Column(name = "mov_id")
  public Long getMovId() {
    return this.movId;
  }

  public void setMovId(Long movId) {
    this.movId = movId;
  }

  /**
   * @return the ffId
   */
  @Column(name = "ff_id")
  public Long getFfId() {
    return ffId;
  }

  /**
   * @param ffId the ffId to set
   */
  public void setFfId(Long ffId) {
    this.ffId = ffId;
  }

  /**
   * @return the objDayNum
   */
  @Column(name = "obj_day_num")
  public Integer getObjDayNum() {
    return objDayNum;
  }

  /**
   * @param objDayNum the objDayNum to set
   */
  public void setObjDayNum(Integer objDayNum) {
    this.objDayNum = objDayNum;
  }

  /**
   * @return the recFileNum
   */
  @Column(name = "rec_file_num")
  public Integer getRecFileNum() {
    return recFileNum;
  }

  /**
   * @param recFileNum the recFileNum to set
   */
  public void setRecFileNum(Integer recFileNum) {
    this.recFileNum = recFileNum;
  }

}
