package com.gwac.model;
// Generated 2017-8-27 10:17:29 by Hibernate Tools 3.6.0

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * ObservationPlan generated by hbm2java
 */
@Entity
@Table(name = "observation_plan_state", schema = "public"
)
public class ObservationPlanState implements java.io.Serializable {

  private long obsPlanId;
  private Long opId;
  private String state;
  private Date ctime;

  @GenericGenerator(name = "generator", strategy = "seqhilo", parameters = {
    @Parameter(name = "max_lo", value = "49"),
    @Parameter(name = "sequence", value = "obs_plan_id_seq")})
  @Id
  @GeneratedValue(generator = "generator")
  @Column(name = "obs_plan_id", unique = true, nullable = false)
  public long getObsPlanId() {
    return this.obsPlanId;
  }

  public void setObsPlanId(long obsPlanId) {
    this.obsPlanId = obsPlanId;
  }
  
  @Column(name = "op_id")
  public long getOpId() {
    return this.opId;
  }

  public void setOpId(long opId) {
    this.opId = opId;
  }

  /**
   * @return the state
   */
  @Column(name = "state")
  public String getState() {
    return state;
  }

  /**
   * @param state the state to set
   */
  public void setState(String state) {
    this.state = state;
  }

  /**
   * @return the ctime
   */
  @Column(name = "ctime")
  public Date getCtime() {
    return ctime;
  }

  /**
   * @param ctime the ctime to set
   */
  public void setCtime(Date ctime) {
    this.ctime = ctime;
  }


}
